apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.metricsname" . }}
  labels:
    {{- include "demo.metricslabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.container.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "demo.podlabels" . | nindent 4 }}
