apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.protocname" . }}
  labels:
    {{- include "demo.protoclabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.container.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.container.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "demo.podlabels" . | nindent 4 }}
