{{- if .Values.container.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.container.serviceAccount }}
{{- end }}
---
{{- if .Values.container.serviceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-role
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
{{- end }}
---
{{- if .Values.container.serviceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.container.serviceAccount }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
{{- if .Values.container.serviceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-lease
subjects:
- kind: ServiceAccount
  name: {{ .Values.container.serviceAccount }}
roleRef:
  kind: ClusterRole
  name: demo-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}